name: Release new version

run-name: Release started by @${{ github.actor }}

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "bot"

      - name: Install dependencies
        run: npm install

      - name: release a new version
        run: |
          npm run release
          VERSION=$(node -p "require('./package.json').version")
          git checkout -b release-${VERSION}
          git push origin release-${VERSION}
          gh pr create --base main --head release-${VERSION} --title "Release ${VERSION}" --body "Automated release of version ${VERSION}"
          PR_NUMBER=$(gh pr list --state open --base main --search "release-${VERSION}" --json number --jq '.[0].number')
          gh pr merge $PR_NUMBER --rebase --delete-branch --auto --admin
          git checkout main
          git pull
          git push --tags
          git checkout develop
          git rebase origin/main
          git push --force-with-lease
